import gradio as gr

from app.config import APP_TITLE, FORECAST_HORIZON_HOURS
from app.data import load_data, split_chronological, replay_prediction
from app.components.snapshot import format_snapshot
from app.components.backtest import build_backtest_section


def build_dashboard() -> gr.Blocks:
    """Build the SmokeClock Gradio dashboard."""
    df = load_data()
    row = df.iloc[-1]
    _, test = split_chronological(df)

    timestamps = [
        ts.strftime("%Y-%m-%d %H:%M IST")
        for ts in test["datetime"]
    ]

    def run_replay(timestamp_text):
        index = timestamps.index(timestamp_text)
        result = replay_prediction(df, index)

        error = abs(result["prediction"] - result["observed"])

        return (
            f"### Historical replay prediction\n"
            f"**Forecast issued:** {result['datetime'].strftime('%Y-%m-%d %H:%M IST')}\n\n"
            f"**Predicted PM2.5:** {result['prediction']:.1f} µg/m³\n\n"
            f"**Observed PM2.5 {FORECAST_HORIZON_HOURS}h later:** "
            f"{result['observed']:.1f} µg/m³\n\n"
            f"**Absolute error:** {error:.1f} µg/m³\n\n"
            f"> This is a historical replay using a model trained only on "
            f"data before the selected test period. It is not a live forecast."
        )

    with gr.Blocks(title=APP_TITLE) as demo:
        gr.Markdown(
            f"""
# SmokeClock

### Wind-aware smoke intelligence for Delhi-NCR

SmokeClock estimates how upwind agricultural-fire activity may affect
future PM2.5 using fire detections, weather, and historical air quality.

> **Historical replay / research prototype** — not official health advice.
"""
        )

        gr.Markdown(format_snapshot(row))

        gr.Markdown("## Historical forecast replay")

        timestamp_dropdown = gr.Dropdown(
            choices=timestamps,
            value=timestamps[0],
            label="Select a held-out forecast timestamp",
        )

        replay_button = gr.Button("Run historical replay")

        replay_output = gr.Markdown()

        replay_button.click(
            fn=run_replay,
            inputs=timestamp_dropdown,
            outputs=replay_output,
        )

        build_backtest_section()

        gr.Markdown(
            f"""
### Evaluation horizon

The evidence panel evaluates a **{FORECAST_HORIZON_HOURS}-hour**
forecast horizon using a chronological October 2025 holdout.

The replay prediction above is generated by training on the earlier
75% of the historical dataset and predicting a held-out observation.
"""
        )

    return demo
